[tool.poetry]
name = "garkbit"
version = "0.1.0"
description = ""
authors = ["Joseph Rawson <joseph.rawson.works@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
